print("I am calculating things")
print("I am calculating 1 x 3%4 to see why the python console doesn't work")
print(1*3%4)
print("doesn't seem right")
print("try 10 x 3%4 should be 1.2")
print(10*3%4)
print("still not right")
print("then try 25*3%4")
print(25*3%4)
print("But that is correct - so why?")
print("try floating point numbers?")
print("10.0*3.0%4.0")
print(10.0*3.0%4.0)
print("is it the size of the number")
print("20 x 3%4 should be 2.4")
print(20*3%4)
print("even worse")
print("its because % is not percent as on a calculator its a modulus so 3%4 is not 0.12.")
print("the calculation would read (25 x 3 = 75) then 75/4 = 18.75 which is 18 remainder 3")
print("the modulus then returns the remainder i.e 3")
